# for production
version: '3.7'
services:
  postgres-database:
    container_name: postgres-database
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ms8744Aol28
      POSTGRES_DB: taxator
    image: postgres:15.1-alpine
    networks:
      - app-network

  app:
    build:
      context: .
    depends_on:
      - postgres-database
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3000:3000'
    environment:
      DB_SEQUELIZE_HOST: postgres-database
      DB_SEQUELIZE_DBNAME: taxator
      DB_SEQUELIZE_USERNAME: postgres
      DB_SEQUELIZE_PASSWORD: Ms8744Aol28
      DB_SEQUELIZE_DIALECT: postgres
#      - DB_SEQUELIZE_URI=postgres://postgres:Ms8744Aol28@192.168.0.2:5432/taxator
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

